In [2]:
import numpy as np
import sys

In [16]:
import time

In [162]:
f = open('data/ks_4_0')

In [163]:
text = f.read()
lines = text.split('\n')
text

'4 11\n8 4\n10 5\n15 8\n4 3\n'

In [163]:
a = np.random.randint(0,5,10)
print(a)
sorted_index = np.argsort(a)
de_sorted_index = np.argsort(sorted_index)
print(a[sorted_index])
a[de_sorted_index[sorted_index]]

[2 1 3 4 2 3 1 2 4 0]
[0 1 1 2 2 2 3 3 4 4]


array([2, 1, 3, 4, 2, 3, 1, 2, 4, 0])

In [ ]:
#bond and brach 2
def solver_tree(file_path):
    #f = open(file=file_path)
    #text = f.read()
    text = file_path #eliminar y descomentar las anteriores
    lines = text.split('\n')
    #lines.remove('') #descoemntar tambien
    first_line = lines[0].split()
    n = int(first_line[0]) 
    K = int(first_line[1])
    
#     print('n:',n)
#     print('K:',K)
        
    lines = np.array([lines[i].split() for i in range(1,len(lines))]).astype(int)
                
    lines = np.append(lines,(lines[:,0]/lines[:,1]).reshape(-1,1),axis=1)
    
    sorted_efficiencies = np.argsort(lines[:,2])[::-1]
    
    lines  = lines[sorted_efficiencies]
    
    de_sorted_efficiencies = np.argsort(sorted_efficiencies)
    
    def relaxed_best(lista_valores,lista_pesos,K):
        value = 0
        for i in range(len(lista_pesos)):
            if lista_pesos[i] < K:
                K -= lista_pesos[i]
                value += lista_valores[i]
            else:
                fraction = K/lista_pesos[i]
                value += fraction * lista_valores[i]
    
        return value
    
    def finder(lista_valores,lista_pesos,lista_eficiencias,valor,K,mejor_previo,lista_decisiones):
        estimacion = relaxed_best(lista_valores,lista_pesos,K)
        if estimacion > mejor_previo:
            

In [195]:
#bond and brach
def solver_tree(file_path):
    #f = open(file=file_path)
    #text = f.read()
    text = file_path #eliminar y descomentar las anteriores
    lines = text.split('\n')
    #lines.remove('') #descoemntar tambien
    first_line = lines[0].split()
    n = int(first_line[0]) 
    K = int(first_line[1])
    
#     print('n:',n)
#     print('K:',K)
        
    lines = np.array([lines[i].split() for i in range(1,len(lines))]).astype(int)
                
    lines = np.append(lines,(lines[:,0]/lines[:,1]).reshape(-1,1),axis=1)
    
    sorted_efficiencies = np.argsort(lines[:,2])[::-1]
    
    lines  = lines[sorted_efficiencies]
    
    de_sorted_efficiencies = np.argsort(sorted_efficiencies)
    
    def relaxed_best(lista_valores,lista_pesos,K):
        value = 0
        for i in range(len(lista_pesos)):
            if lista_pesos[i] < K:
                K -= lista_pesos[i]
                value += lista_valores[i]
            else:
                fraction = K/lista_pesos[i]
                value += fraction * lista_valores[i]
    
        return value
    
    class tree():
        def __init__(self,lista_valores,lista_pesos,capacidad,lista_decisiones,valor,mejor_calculado,mejores_decisio):
            self.lista_valores = lista_valores
            self.lista_pesos = lista_pesos
            self.capacidad = capacidad
            self.lista_decisiones = lista_decisiones.copy()
            self.valor = valor
            self.mejor_calculado = mejor_calculado
            self.nodo_1 = None
            self.tree_1 = None
            self.nodo_0 = None
            self.tree_0 = None
            self.node_list = []
            self.mejores_decisio = mejores_decisio
            
        def run(self):
            self.nodo_1 = node(lista_valores = self.lista_valores,
                               lista_pesos = self.lista_pesos,
                               capacidad = self.capacidad,
                               valor = self.valor,
                               agrego = True,
                               lista_decisiones = self.lista_decisiones)
            self.nodo_1.calcular()
            
            #self.node_list.append(self.nodo_1)
            
            if self.nodo_1.valor > self.mejor_calculado:
                self.mejor_calculado = self.nodo_1.valor
                self.mejores_decisio = self.nodo_1.lista_decisiones
            
#             print('node calculation si: c:',self.nodo_1.capacidad,'v:',self.nodo_1.valor,
#                   '\tMejor',self.mejor_calculado,
#                   '\tEstimado:',self.nodo_1.estimacion,
#                   ' \tLista_valores',self.nodo_1.lista_valores,
#                   '\t',self.nodo_1.lista_decisiones)

            if ((len(self.lista_valores)>1) & self.nodo_1.nodo_valido) & (self.nodo_1.estimacion > self.mejor_calculado):
                self.tree_1 = tree(lista_valores = self.lista_valores[1:],
                                   lista_pesos = self.lista_pesos[1:],
                                   capacidad = self.nodo_1.capacidad,
                                   lista_decisiones = self.nodo_1.lista_decisiones,
                                   valor=self.nodo_1.valor,
                                   mejor_calculado=self.mejor_calculado,
                                   mejores_decisio = self.mejores_decisio)
                self.tree_1.run()
                
                if self.tree_1.mejor_calculado > self.mejor_calculado:
                    self.mejor_calculado = self.tree_1.mejor_calculado
                    self.mejores_decisio = self.tree_1.mejores_decisio
                    
                    
                #self.node_list.append(self.tree_1.node_list)
            else:
#                 print('nodo esquivado')
                 pass

            self.nodo_0 = node(lista_valores = self.lista_valores,
                               lista_pesos = self.lista_pesos,
                               capacidad = self.capacidad,
                               valor = self.valor,
                               agrego = False,
                               lista_decisiones = self.lista_decisiones)
            self.nodo_0.calcular()
            
            #self.node_list.append(self.nodo_0)
            
            if self.nodo_0.valor > self.mejor_calculado:
                self.mejor_calculado = self.nodo_0.valor
                self.mejores_decisio = self.nodo_0.lista_decisiones

            
#             print('node calculation no: c:',self.nodo_0.capacidad,'v:',self.nodo_0.valor,
#                   '\tMejor',self.mejor_calculado,
#                   '\tEstimado:',
#                   self.nodo_0.estimacion,
#                   ' \tLista_valores',self.nodo_0.lista_valores,
#                   '\t',self.nodo_0.lista_decisiones)
            
            if ((len(self.lista_valores)>2) & self.nodo_0.nodo_valido) & (self.nodo_0.estimacion > self.mejor_calculado):
                self.tree_0 = tree(lista_valores = self.lista_valores[1:],
                                   lista_pesos = self.lista_pesos[1:],
                                   capacidad = self.nodo_0.capacidad,
                                   lista_decisiones = self.nodo_0.lista_decisiones,
                                   valor=self.nodo_0.valor,
                                   mejor_calculado=self.mejor_calculado,
                                   mejores_decisio = self.mejores_decisio)
                
                self.tree_0.run()
                if self.tree_0.mejor_calculado > self.mejor_calculado:
                    self.mejor_calculado = self.tree_0.mejor_calculado
                    self.mejores_decisio = self.tree_0.mejores_decisio

            
                #self.node_list.append(self.tree_0.node_list)
            else:
#                 print('nodo esquivado')
                 pass
            
  
    class node():
        def __init__(self,lista_valores,lista_pesos,capacidad,valor,agrego,lista_decisiones):
            self.lista_valores = lista_valores
            self.lista_pesos = lista_pesos
            self.capacidad = capacidad
            self.valor = valor
            self.agrego = agrego
            self.nodo_valido = True
            self.lista_decisiones = lista_decisiones.copy()
            
                
        def calcular(self):
            if self.agrego & (self.lista_pesos[0] > self.capacidad):
                self.valor = -1
                self.capacidad = self.capacidad - self.lista_pesos[0]
                self.estimacion = -1
                self.nodo_valido = False
                self.lista_decisiones.append(-1)
            
            if self.agrego & self.nodo_valido:
                self.estimacion = self.valor + self.lista_valores[0] + relaxed_best(self.lista_valores[1:],self.lista_pesos[1:],self.capacidad)
                self.valor += self.lista_valores[0]
                self.lista_decisiones.append(1)
                self.capacidad = self.capacidad - self.lista_pesos[0]

            
            elif ~self.agrego & self.nodo_valido:
                self.estimacion = self.valor  + relaxed_best(self.lista_valores[1:],self.lista_pesos[1:],self.capacidad)
                self.lista_decisiones.append(0)
                #self.capacidad = self.capacidad - self.lista_pesos[0]
            #print(self.lista_decisiones)

                
    initial_tree = tree(lista_valores=lines[:,0],lista_pesos=lines[:,1],capacidad=K,lista_decisiones=[],valor=0,mejor_calculado=0,mejores_decisio=[])
    initial_tree.run()
    
    formated_mejores_decisiones = np.concatenate((np.array(initial_tree.mejores_decisio),np.zeros(n-len(initial_tree.mejores_decisio))))#[de_sorted_efficiencies] # a las deciciones, le agrego los 0 que falten, concateno y despues ordeno
    formated_mejores_decisiones = formated_mejores_decisiones.astype(int).astype(str)
    solution = f'{int(initial_tree.mejor_calculado)} {1}\n{" ".join(formated_mejores_decisiones)}'#'{" ".join(list(traceback_decition_x.astype(str)))}'
    
    #print(np.append(lines[:,:2][de_sorted_efficiencies].astype(int),formated_mejores_decisiones.astype(int).reshape(-1,1),axis=1))

    
    return solution
    return int(initial_tree.mejor_calculado),list(np.concatenate((np.array(initial_tree.mejores_decisio),np.zeros(n-len(initial_tree.mejores_decisio))))[de_sorted_efficiencies])

In [260]:
n = 25
K = 25
items_list = [f'{n} {K}']+[f'{np.random.randint(1,2*n)} {np.random.randint(0,1*K/n)+1}' for i in range(n)]
item_string = '\n'.join(items_list)
item_string

'25 25\n47 1\n2 1\n35 1\n30 1\n48 1\n14 1\n19 1\n45 1\n23 1\n6 1\n39 1\n46 1\n24 1\n39 1\n21 1\n13 1\n32 1\n8 1\n7 1\n24 1\n30 1\n12 1\n30 1\n22 1\n12 1'

In [246]:
t0 = time.time()
print(solver_tree(item_string))
t1 = time.time()
print(t1-t0)

611 1
1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1.3663582801818848


In [247]:
t0 = time.time()
print(solver_O(item_string))
t1 = time.time()
print(t1-t0)

611 1
1 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 0 0 0 1 0 1 0
0.08380293846130371


In [229]:
solver_O_2(item_string)

OSError: [Errno 22] Invalid argument: '30 1000\n4 192\n4 29\n22 662\n31 387\n34 448\n33 34\n34 277\n14 71\n4 176\n2 487\n25 575\n13 604\n6 597\n20 200\n6 97\n42 43\n10 187\n43 473\n21 22\n53 414\n5 219\n7 442\n47 476\n9 510\n55 54\n20 303\n25 93\n30 421\n22 30\n41 201'

In [63]:
#O(n,K)
def solver_O(file_path):
    #f = open(file=file_path)
    #text = f.read()
    text = file_path #eliminar y descomentar las anteriores
    lines = text.split('\n')
    #lines.remove('') #descoemntar tambien
    first_line = lines[0].split()
    n = int(first_line[0]) 
    K = int(first_line[1])
    
#     print('n:',n)
#     print('K:',K)
    
    lines = np.array([lines[i].split() for i in range(1,len(lines))]).astype(int)
    
    #print('Lines:\n',lines)
    
    #Planteo de solcion por dynamic programing
    
    O = np.zeros(shape=(K+1,n),dtype=int)
    
    for i in range(K+1):
        if i >= lines[0,1]:
            O[i,0] = lines[0,0]
            
    for j in range(1,n): #voy columna por columna de la tabla O
        #print(j/(n-1)*100,end='\r') #para ver el avance
        if lines[j,1] > K: #Verifico si el objeto es mas grande que la bolsa
            O[:K+1,j] = O[:K+1,j-1] #copio la columna entera
        else:
            O[:lines[j,1],j] = O[:lines[j,1],j-1] #sino copio las filas hasta uno menos que el peso del objeto
        for i in range(lines[j,1],K+1): #verifico las filas desde el peso en adelane si mejoro el valos de O
            if (O[i,j-1] > O[i-lines[j,1],j-1] + lines[j,0]):
                O[i,j] = O[i,j-1]
            elif (i - lines[j,1] >= 0):
                O[i,j] = O[i-lines[j,1],j-1] + lines[j,0]

#     print(O)
    
    traceback_k = K
    traceback_decition_x = np.zeros(n,dtype=int)
    for i in range(n-1,-1,-1):
        if O[traceback_k,i] != O[traceback_k,i-1]:
            traceback_k -= lines[i,1]
            traceback_decition_x[i] = 1
            #print('traceback_k:',traceback_k)
            #print('traceback_decition_x:',traceback_decition_x)
                
    #print(traceback_decition_x)
    
    solution = f'{O[K,n-1]} {1}\n{" ".join(list(traceback_decition_x.astype(str)))}'
    
    #print(np.append(lines, traceback_decition_x.reshape(-1,1),axis=1))

    
    return solution

In [132]:
#O(n,K)
def solver_O_2(file_path):
    f = open(file=file_path)
    text = f.read()
    #text = file_path #eliminar y descomentar las anteriores
    lines = text.split('\n')
    lines.remove('') #descoemntar tambien
    first_line = lines[0].split()
    n = int(first_line[0]) 
    K = int(first_line[1])
    
#     print('n:',n)
#     print('K:',K)
    
    lines = np.array([lines[i].split() for i in range(1,len(lines))]).astype(int)
    
    eficiencies = (lines[:,0]/lines[:,1])
    
    sorted_efficiencies = np.argsort(eficiencies)[::-1]
    
    lines  = lines[sorted_efficiencies]
    
    de_sorted_efficiencies = np.argsort(sorted_efficiencies)   
    
    #print('Lines:\n',lines)
    
    #Planteo de solcion por dynamic programing
    
    O = np.zeros(shape=(K+1,n),dtype=int)
    
    for i in range(K+1):
        if i >= lines[0,1]:
            O[i,0] = lines[0,0]
            
    for j in range(1,n): #voy columna por columna de la tabla O
        #print(j/(n-1)*100,end='\r') #para ver el avance
        if lines[j,1] > K: #Verifico si el objeto es mas grande que la bolsa
            O[:K+1,j] = O[:K+1,j-1] #copio la columna entera
        else:
            O[:lines[j,1],j] = O[:lines[j,1],j-1] #sino copio las filas hasta uno menos que el peso del objeto
        for i in range(lines[j,1],K+1): #verifico las filas desde el peso en adelane si mejoro el valos de O
            if (O[i,j-1] > O[i-lines[j,1],j-1] + lines[j,0]):
                O[i,j] = O[i,j-1]
            elif (i - lines[j,1] >= 0):
                O[i,j] = O[i-lines[j,1],j-1] + lines[j,0]

#     print(O)
    
    traceback_k = K
    traceback_decition_x = np.zeros(n,dtype=int)
    for i in range(n-1,-1,-1):
        if O[traceback_k,i] != O[traceback_k,i-1]:
            traceback_k -= lines[i,1]
            traceback_decition_x[i] = 1
            #print('traceback_k:',traceback_k)
            #print('traceback_decition_x:',traceback_decition_x)
                
    #print(traceback_decition_x)
    
    solution = f'{O[K,n-1]} {1}\n{" ".join(list(traceback_decition_x[de_sorted_efficiencies].astype(str)))}'
    
    return solution

In [380]:
solver(item_string)

n: 10
K: 10


31.28571428571429

In [261]:
greedy(item_string)

[[47  1]
 [ 2  1]
 [35  1]
 [30  1]
 [48  1]
 [14  1]
 [19  1]
 [45  1]
 [23  1]
 [ 6  1]
 [39  1]
 [46  1]
 [24  1]
 [39  1]
 [21  1]
 [13  1]
 [32  1]
 [ 8  1]
 [ 7  1]
 [24  1]
 [30  1]
 [12  1]
 [30  1]
 [22  1]
 [12  1]]
[[47.  1. 47.]
 [ 2.  1.  2.]
 [35.  1. 35.]
 [30.  1. 30.]
 [48.  1. 48.]
 [14.  1. 14.]
 [19.  1. 19.]
 [45.  1. 45.]
 [23.  1. 23.]
 [ 6.  1.  6.]
 [39.  1. 39.]
 [46.  1. 46.]
 [24.  1. 24.]
 [39.  1. 39.]
 [21.  1. 21.]
 [13.  1. 13.]
 [32.  1. 32.]
 [ 8.  1.  8.]
 [ 7.  1.  7.]
 [24.  1. 24.]
 [30.  1. 30.]
 [12.  1. 12.]
 [30.  1. 30.]
 [22.  1. 22.]
 [12.  1. 12.]]
[[48.  1. 48.]
 [47.  1. 47.]
 [46.  1. 46.]
 [45.  1. 45.]
 [39.  1. 39.]
 [39.  1. 39.]
 [35.  1. 35.]
 [32.  1. 32.]
 [30.  1. 30.]
 [30.  1. 30.]
 [30.  1. 30.]
 [24.  1. 24.]
 [24.  1. 24.]
 [23.  1. 23.]
 [22.  1. 22.]
 [21.  1. 21.]
 [19.  1. 19.]
 [14.  1. 14.]
 [13.  1. 13.]
 [12.  1. 12.]
 [12.  1. 12.]
 [ 8.  1.  8.]
 [ 7.  1.  7.]
 [ 6.  1.  6.]
 [ 2.  1.  2.]]


'626 0\n1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1'

In [398]:
greedy('data/ks_4_0')

[[ 8  4]
 [10  5]
 [15  8]
 [ 4  3]]


'18 0\n1 1 0 0'

In [396]:
#Greedy
def greedy(file_path):
    f = open(file=file_path)
    text = f.read()
    #text = file_path #eliminar y descomentar las anteriores
    lines = text.split('\n')
    lines.remove('') #descoemntar tambien
    first_line = lines[0].split()
    n = int(first_line[0]) 
    K = int(first_line[1])
    
    #  print('n:',n)
    #  print('K:',K)
    
    lines = np.array([lines[i].split() for i in range(1,len(lines))]).astype(int)
        
    #print(lines)
    
    lines = np.append(lines,(lines[:,0]/lines[:,1]).reshape(-1,1),axis=1)
    
    #print(lines)
    
    sorted_val = np.argsort(lines[:,0])[::-1]
    
    sorted_ef = np.argsort(lines[sorted_val,2])[::-1]
        
    sorted_lines = lines[sorted_val,:][sorted_ef,:]
    
    #print(sorted_lines)
    
    cargo = 0
    value = 0
    response = np.zeros(n,dtype=int)
        
    for i in range(n):
        if cargo + sorted_lines[i,1] < K:
            cargo += sorted_lines[i,1]
            value += sorted_lines[i,0]
            response[sorted_val[sorted_ef[i]]] = 1
    
    solution = f'{value.astype(int)} {0}\n{" ".join(list(response.astype(str)))}'
    
    return solution

In [388]:
def greedy_2(file_path):
    #f = open(file=file_path)
    #text = f.read()
    text = file_path #eliminar y descomentar las anteriores
    lines = text.split('\n')
    #lines.remove('') #descoemntar tambien
    first_line = lines[0].split()
    n = int(first_line[0]) 
    K = int(first_line[1])
    
#     print('n:',n)
#     print('K:',K)
    
    lines = np.array([lines[i].split() for i in range(1,len(lines))]).astype(int)
    
    #print(lines)
    
    lines = np.append(lines,(lines[:,0]/lines[:,1]).reshape(-1,1),axis=1)
        
    sorted_val = np.argsort(lines[:,0])[::-1]
    sorted_wei = np.argsort(lines[:,1])
    sorted_eff = np.argsort(lines[:,2])[::-1]
    sorted_val_eff = np.lexsort((lines[:,2],lines[:,0]))[::-1]
    sorted_eff_val = np.lexsort((lines[:,0],lines[:,2]))[::-1]
    sorted_val_wei = np.lexsort((-lines[:,1],lines[:,0]))[::-1]
    sorted_wei_val = np.lexsort((lines[:,0],-lines[:,1]))[::-1]
    
    sorts = [sorted_val,sorted_wei,sorted_eff,sorted_val_eff,sorted_eff_val,sorted_val_wei,sorted_wei_val]
    
    values = np.array([])
    responses = np.array([])
    
    for i in sorts:
        
        cargo = 0
        value = 0
        sorted_lines = lines[i]
        response = np.zeros(n,dtype=int)
        
        for j in range(n):
            if cargo + sorted_lines[j,1] < K:
                cargo += sorted_lines[j,1]
                value += sorted_lines[j,0]
                response[i[j]] = 1
        
        values = np.append(values,value)
        responses = np.append(responses,response)
        
    responses = np.reshape(responses,(len(sorts),-1))
    
    index = np.argmax(values)
    
    value = values[index]
    response = responses[index]
    
    solution = f'{value.astype(int)} {0}\n{" ".join(list(response.astype(str)))}'
    
    return solution


In [389]:
greedy_2(item_string)

[[3 5]
 [1 6]
 [7 5]
 [6 1]
 [1 6]
 [3 1]
 [5 8]
 [7 4]
 [7 9]
 [9 5]
 [3 6]
 [6 9]
 [4 8]
 [1 4]
 [4 8]
 [5 3]
 [2 3]
 [1 5]
 [7 1]
 [5 1]]


'30 0\n0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0'

In [326]:
n = 20
K = 10
items_list = [f'{n} {K}']+[f'{np.random.randint(1,K)} {np.random.randint(1,K)}' for i in range(n)]
item_string = '\n'.join(items_list)
item_string

'20 10\n3 5\n1 6\n7 5\n6 1\n1 6\n3 1\n5 8\n7 4\n7 9\n9 5\n3 6\n6 9\n4 8\n1 4\n4 8\n5 3\n2 3\n1 5\n7 1\n5 1'