In [1]:
print('hola')

hola


In [2]:
import pandas as pd

In [17]:
data = pd.DataFrame()

In [18]:
data

Empty DataFrame
Columns: []
Index: []

In [19]:
data.loc[0,3] = 10
data

3
0  10.0

In [20]:
data.loc[4,5] = 20
data

3     5
0  10.0   NaN
4   NaN  20.0

In [21]:
a = 99

In [23]:
# data.loc[[9,10],[9,10]] = a

In [24]:
data.loc[9,9] = a
data.loc[10,10] = a
data

3     5     9     10
0   10.0   NaN   NaN   NaN
4    NaN  20.0   NaN   NaN
9    NaN   NaN  99.0   NaN
10   NaN   NaN   NaN  99.0

In [16]:
a = 1
data

3     5     9     10
0   10.0   NaN   NaN   NaN
4    NaN  20.0   NaN   NaN
9    NaN   NaN  99.0   NaN
10   NaN   NaN   NaN  99.0

In [25]:
import numpy as np

In [34]:
array = np.random.uniform(size=(4,3))
array

array([[0.81262096, 0.61252607, 0.72175532],
       [0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076],
       [0.67413362, 0.44183317, 0.43401399]])

In [36]:
np.argsort(array, axis=1)

array([[1, 2, 0],
       [0, 2, 1],
       [1, 2, 0],
       [2, 1, 0]], dtype=int64)

In [42]:
isinstance(3,int)

True

In [15]:
from pulp import *

In [16]:
prob = LpProblem("The Whiskas Problem", LpMinimize)


In [17]:
LpVariable("example", None, 100)

example

In [18]:
LpVariable("example", upBound = 100)

example

In [19]:
x1 = LpVariable("ChickenPercent", 0, None, LpInteger)
x2 = LpVariable("BeefPercent", 0)

In [20]:
prob += 0.013 * x1 + 0.008 * x2, "Total Cost of Ingredients per can"

In [21]:
prob += x1 + x2 == 100, "PercentagesSum"
prob += 0.100 * x1 >= 8.0 - 0.200 * x2, "ProteinRequirement"
prob += 0.080 * x1 + 0.100 * x2 >= 6.0, "FatRequirement"
prob += 0.001 * x1 + 0.005 * x2 <= 2.0, "FibreRequirement"
prob += 0.002 * x1 + 0.005 * x2 <= 0.4, "SaltRequirement"

In [22]:
prob.writeLP("WhiskasModel.lp")

[BeefPercent, ChickenPercent]

In [25]:
print(listSolvers(onlyAvailable = True))

['GLPK_CMD']


In [26]:
prob.solve()

1

In [10]:
print("Status:", LpStatus[prob.status])

Status: Optimal


In [13]:
import pulp as pl
solver_list = pl.listSolvers()
solver_list

['GLPK_CMD',
 'PYGLPK',
 'CPLEX_CMD',
 'CPLEX_PY',
 'GUROBI',
 'GUROBI_CMD',
 'MOSEK',
 'XPRESS',
 'XPRESS',
 'XPRESS_PY',
 'PULP_CBC_CMD',
 'COIN_CMD',
 'COINMP_DLL',
 'CHOCO_CMD',
 'MIPCL_CMD',
 'SCIP_CMD',
 'HiGHS_CMD']

In [9]:
import pulp

# Create a PuLP problem
prob = pulp.LpProblem("Simple MIP Problem", pulp.LpMinimize)

# Define the decision variables
x = pulp.LpVariable('x', lowBound=0, cat='Integer')
y = pulp.LpVariable('y', lowBound=0, cat='Integer')
z = pulp.LpVariable('z', lowBound=0, cat='Integer')

# Define the objective function
prob += 5 * x + 5 * y + z

# Define the constraints
prob += 4 * x + 3 * y >= 80
prob += 4 * x + 2 * y >= 100
prob += x >= z
prob += y >= z
prob += x >= 5
prob += y >= 5
prob += z >= 2

# Solve the problem using GLPK
prob.solve(pulp.GLPK_CMD())

# Access the solution status and optimal objective value
status = pulp.LpStatus[prob.status]
objective_value = pulp.value(prob.objective)

# Access the variable values
solution = {}
for var in prob.variables():
    solution[var.name] = var.varValue

print("Solution Status:", status)
print("Objective Value:", objective_value)
print("Solution:")
for var, value in solution.items():
    print(var, "=", value)


Solution Status: Optimal
Objective Value: 142
Solution:
x = 23
y = 5
z = 2


In [1]:
import pulp as pl

['GLPK_CMD',
 'PYGLPK',
 'CPLEX_CMD',
 'CPLEX_PY',
 'GUROBI',
 'GUROBI_CMD',
 'MOSEK',
 'XPRESS',
 'XPRESS',
 'XPRESS_PY',
 'PULP_CBC_CMD',
 'COIN_CMD',
 'COINMP_DLL',
 'CHOCO_CMD',
 'MIPCL_CMD',
 'SCIP_CMD',
 'HiGHS_CMD']

In [2]:
pl.listSolvers(onlyAvailable=True)

['PULP_CBC_CMD']

In [12]:
for i in dict(zip(range(8), range(9, 17))).keys():
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [4]:
3 in range(6)

True

In [15]:
import pandas as pd
import numpy as np

In [21]:
pd.concat((pd.Series(np.zeros(10), name='first'),pd.Series(np.zeros(10), name='second')), axis=1)

first  second
0    0.0     0.0
1    0.0     0.0
2    0.0     0.0
3    0.0     0.0
4    0.0     0.0
5    0.0     0.0
6    0.0     0.0
7    0.0     0.0
8    0.0     0.0
9    0.0     0.0

In [31]:
np.stack((np.zeros(10), np.ones(10)), axis=1)

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [1]:
import numpy as np

In [24]:
a = np.array([[0.2,3],[0.5,1],[3,5]])
print(a)

[[0.2 3. ]
 [0.5 1. ]
 [3.  5. ]]


In [25]:
print(np.argsort(a, axis=1))

[[0 1]
 [0 1]
 [0 1]]


In [26]:
print(np.argsort(a, axis=0))

[[0 1]
 [1 0]
 [2 2]]


In [27]:
a

array([[0.2, 3. ],
       [0.5, 1. ],
       [3. , 5. ]])

In [28]:
a[[[0,1],[0,1],[0,1]]]

array([[[0.2, 3. ],
        [0.5, 1. ]],

       [[0.2, 3. ],
        [0.5, 1. ]],

       [[0.2, 3. ],
        [0.5, 1. ]]])

In [32]:
print(a<2)

[[ True False]
 [ True  True]
 [False False]]


In [30]:
a[a<2]

array([0.2, 0.5, 1. ])

In [37]:
my_list = ['hola','buenos dias','queso',3]

'_'.join(str(x) for x in my_list)

'hola_buenos dias_queso_3'

In [43]:
np.array(range(5))[[True,True,False,True,False]]

TypeError: range indices must be integers or slices, not list